# Generated by Django 6.0.5 on 2026-05-09 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issuer', models.CharField(max_length=200)),
                ('icon', models.CharField(help_text="FontAwesome class, e.g. 'fa-solid fa-code'", max_length=100)),
                ('icon_color', models.CharField(choices=[('blue', 'Neon Blue'), ('purple', 'Neon Purple')], default='blue', max_length=20)),
                ('verify_url', models.URLField(help_text='Link to verify the certification')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Snehal Galande', max_length=100)),
                ('title', models.CharField(default='Data Engineer', max_length=200)),
                ('subtitle', models.CharField(default='Building scalable architectures & intelligent pipelines.', max_length=300)),
                ('greeting_code', models.CharField(default='// SNEHAL.INIT()', help_text='The terminal-style greeting text', max_length=100)),
                ('terminal_command', models.CharField(default='./execute_intro.sh', max_length=100)),
                ('terminal_output', models.CharField(default='Hello, world! I engineer data ecosystems.', max_length=300)),
                ('about_text', models.TextField(default='I am a passionate Data Engineer focused on transforming raw data into actionable insights. I design, build, and maintain robust, scalable data architectures and processing pipelines.')),
                ('about_text_2', models.TextField(blank=True, default='My expertise bridges the gap between software engineering and data science, ensuring data is reliable, accessible, and high-quality for downstream analytics and machine learning models.')),
                ('resume_link', models.URLField(blank=True, default='', help_text='URL to your resume (e.g. Google Drive link)')),
                ('email', models.EmailField(default='hello@example.com', max_length=254)),
                ('contact_message', models.TextField(default="I'm currently open for new opportunities to build scalable systems. Whether you have a question or just want to say hi, my inbox is always open!")),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('github_url', models.URLField(blank=True, default='')),
                ('live_url', models.URLField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Skill Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(help_text="e.g. 'GitHub', 'LinkedIn'", max_length=100)),
                ('url', models.URLField()),
                ('icon', models.CharField(help_text="FontAwesome class, e.g. 'fa-brands fa-github'", max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text="FontAwesome class, e.g. 'fa-solid fa-database'", max_length=100)),
                ('icon_color', models.CharField(choices=[('blue', 'Neon Blue'), ('purple', 'Neon Purple')], default='blue', max_length=20)),
                ('value', models.CharField(help_text="e.g. '10TB+' or '99.9%'", max_length=50)),
                ('label', models.CharField(help_text="e.g. 'Data Processed'", max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='core.project')),
            ],
            options={
                'verbose_name_plural': 'Project Technologies',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.skillcategory')),
            ],
        ),
    ]
