# Generated by Django 6.0.5 on 2026-05-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cta_text',
            field=models.CharField(blank=True, default='Explore Pipelines', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='footer_text',
            field=models.CharField(blank=True, default='v2.0.0 — Django Powered', max_length=100),
        ),
    ]
