# Generated by Django 5.2.14 on 2026-05-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_certification_id_alter_profile_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a certification image', null=True, upload_to='certifications/'),
        ),
        migrations.AddField(
            model_name='certification',
            name='image_url',
            field=models.URLField(blank=True, default='', help_text='Or paste a certification image URL'),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a project image', null=True, upload_to='projects/'),
        ),
        migrations.AddField(
            model_name='project',
            name='image_url',
            field=models.URLField(blank=True, default='', help_text='Or paste a project image URL'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='icon',
            field=models.CharField(blank=True, help_text="FontAwesome class, e.g. 'fa-solid fa-code'", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='certification',
            name='icon_color',
            field=models.CharField(blank=True, choices=[('blue', 'Neon Blue'), ('purple', 'Neon Purple')], default='blue', max_length=20, null=True),
        ),
    ]
